### ISSUE TITLE
Import block-list from Mastodon

### ISSUE THREAD

**Issue by nichu42** [Fediseer/FediseerGUI#121]
Please add the possibility to import block-lists that have been exported from Mastodon.

The exported csv contains the following:

domain,severity,reject_media,reject_reports,public_comment,obfuscate

example:
domain.tld,suspend,false,false,"racism, discrimination, lolicon",true

I suppose we'll only need domain, severity and public_comment for Fediseer.
severity is either suspend (censor) or silence (treat as hesitated?)
public_comment is in the format "free string", and could be treated as "reason 1, reason 2, reason 3"

(referring to https://matrix.to/#/!vzuoKDBMbcFToIJwxv:discuss.online/$E4paE0mlzpYm1sKfeuG0Gy2b1ysIqV22PJ2Rpl-c4R0?via=matrix.org&via=lemmy.world&via=aria-net.org)

**Comment by RikudouSage** [comment]
Any particular reason why you want to use csv instead of importing from api?

**Comment by nichu42** [comment]
Is importing by API = sync?
That didn't do anything for me.

**Comment by RikudouSage** [comment]
Nope, not currently, but I can download the reasons using api and I think it's better than importing csv, I was just curious if there's a reason why you want to do it using csv.

**Comment by nichu42** [comment]
Ah, I see.
No, API is absolutely fine.

I was suggesting CSV import only due to my limited knowledge & imagination. 😉
