### ISSUE TITLE
move button is not reliably displayed

### ISSUE THREAD

**Issue by Tealk** [Fediseer/FediseerGUI#136]
it seems that the button is not loaded reliably when the list is very long.
Maybe a problem with the cache?

![image](https://github.com/Fediseer/FediseerGUI/assets/12276250/1bdee43d-cb2a-4a21-b8b2-22dc7a92959b)

**Comment by RikudouSage** [comment]
We didn't really anticipate someone having thousands of hesitations. The api will need to adapt to that and afterwards the GUI can.

**Comment by Tealk** [comment]
github-actions bot is extremely annoying, can't you create a label that prevents the bot from closing the topic?
