### ISSUE TITLE
Language color

### ISSUE THREAD

**Issue by Tealk** [Fediseer/FediseerGUI#161]
![image](https://github.com/Fediseer/FediseerGUI/assets/12276250/d33eb68d-7ec1-4edc-9be3-bf6211e16d4e)

**Comment by Tealk** [comment]
Firefox 118.0.2

**Comment by RikudouSage** [comment]
I have 118.0.1 and it doesn't happen, I'm almost sure they didn't cause it in one minor upgrade. Do you have any addons that might be causing this?

**Comment by Tealk** [comment]
![image](https://github.com/Fediseer/FediseerGUI/assets/12276250/4194d805-91a1-465f-ab9e-8af15ab4a7de)

Private Browser Window, no Addons ore something else, Light Theme.
