### ISSUE TITLE
Allow resetting API key directly on the UI

### ISSUE THREAD

**Issue by db0** [Fediseer/FediseerGUI#187]
The password reset endpoint supports returning the new API key directly to the user (as opposed to PMing it to the admin), by setting `  "return_new_key": true` on the PATCH.

This is used when the admin does not receive the PM for any reason, or if they need to reset it without getting the password stored in their DB

**Comment by RikudouSage** [comment]
It's done like that already (see [here](https://github.com/Fediseer/FediseerGUI/blob/master/src/app/services/fediseer-api.service.ts#L466)). I don't think it's used without it anywhere in the code. Feel free to reopen if I missed something.

**Comment by db0** [comment]
Ah ok, so the GUI always returns it directly on the browser? Gotcha.
