### ISSUE TITLE
Add ability to revoke own guarantee

### ISSUE THREAD

**Issue by SmallPatatas** [Fediseer/FediseerGUI#54]
An instance which solicits a guarantee may receive one from an unknown/potentially untrustworthy instance. Ability to revoke may be important, especially in these early adoption days, to avoid larger issues in the future.

Revoking your own guarantee is possible via the API but not yet in the GUI, as far as I can tell.

Method explained here: 

https://github.com/Fediseer/fediseer/issues/24#issuecomment-1722550399

Thanks!

**Comment by RikudouSage** [comment]
It should already be possible to do here: https://gui.fediseer.com/guarantees/my

Do you have any trouble with the feature?

**Comment by SmallPatatas** [comment]
Maybe I do not see it, but it looks like I can revoke a guarantee that I have given, but I cannot revoke the guarantee given to me by another instance.

**Comment by RikudouSage** [comment]
Ah, I misunderstood.

**Comment by SmallPatatas** [comment]
No worries, thanks!
