### ISSUE TITLE
Enhancement - Custom Instances: add some more info to the list

### ISSUE THREAD

**Issue by Antik79** [Fediseer/FediseerGUI#73]
Since there is a lot of whitespace:
![image](https://github.com/Fediseer/FediseerGUI/assets/3721299/a9cc8746-484b-4a9f-aef4-78fc698f66a5)

You could add some info to that list such as the amount of censures, amount of hesitations and maybe top 3 tags?
lemmy.world - censures: 78 - hesitations: 2 - tags: fascism, unmoderated, spam

**Comment by RikudouSage** [comment]
@db0 Can we get censures amount and hesitations amount as part of instance detail response? I can't get this information in any reasonable way right now - I'd have to send a http request for each instance separately.

**Comment by db0** [comment]
you cannot get censures, because that is a relative count and I don't want people to think there is a "global" censure count. I think it does report endorsement count.

**Comment by db0** [comment]
One option is to cache this info, if the user has visited those pages before, or a button to do so?

**Comment by RikudouSage** [comment]
I though @Antik79 meant censures/hesitations and tags given, not received? Or am I wrong?

**Comment by db0** [comment]
That would be just an extra API calls to censures given with only that server name when opening this page (maybe cache it once per session?)

**Comment by RikudouSage** [comment]
@db0 It would be an api call for every guaranteed instance, very ineffective.

**Comment by db0** [comment]
Not for your own censures. That would just be just one call to `/api/v1/censures/<your instance>`

**Comment by RikudouSage** [comment]
But that's not for your own censures, it's for all instances

**Comment by RikudouSage** [comment]
I know, but what @Antik79 is asking, is to display this information for all instances in the select box. Which means I would have to do the same request for every guaranteed instance, which means 242 requests as of now.

**Comment by db0** [comment]
ye that wouldn't work. But what you can do is give the info about the displayed instances according to what selection is selected in the `censures` tab. So assuming it wasn't modified, you would be able to display amount of censures, and top 3 tags from `lemmy.dbzer0.com, lemming.world, lemmy.world`.
