### ISSUE TITLE
Show number of guarantees

### ISSUE THREAD

**Issue by Tealk** [Fediseer/FediseerGUI#76]
On the one hand you would know how many you can still spend, on the other hand it would prevent confusion because it is not easily apparent that there may only be 20 pieces.

![image](https://github.com/Fediseer/FediseerGUI/assets/12276250/64cb077a-86a8-47bc-8864-44dbd59ef7f7)

**Comment by RikudouSage** [comment]
@db0 Can we get some endpoint with this information? I wouldn't like to hardcode it.

**Comment by Tealk** [comment]
Dear bot please leave the ticket open

**Comment by Tealk** [comment]
Still an open suggestion

**Comment by Tealk** [comment]
Thats sad :(
