### ISSUE TITLE
Accout Switch issue

### ISSUE THREAD

**Issue by Tealk** [Fediseer/FediseerGUI#81]
When I press Account Switch, I see the following window:
![image](https://github.com/Fediseer/FediseerGUI/assets/12276250/2a86d58f-66e2-4015-82d9-6be6c14c0d61)

**Comment by RikudouSage** [comment]
Are you logged in?

**Comment by Tealk** [comment]
yes
![image](https://github.com/Fediseer/FediseerGUI/assets/12276250/45557c4f-9444-40c2-8e95-8a483730e31b)

**Comment by RikudouSage** [comment]
It *may* be fixed by #82. Though I'm not sure, I'll let you know when it's released.

**Comment by Tealk** [comment]
fixed with d226175500ef1f6be6adf4e9f831aa0fc9a24eaa
