### ISSUE TITLE
Feature - "Upgrade" and "Downgrade" instances from Hesitations and Censures

### ISSUE THREAD

**Issue by Antik79** [Fediseer/FediseerGUI#83]
Would be nice to have a "one click" option to move an instance from your hesitations to your censures list and the other way around.

Preferably also the same with an instance that is in your guarantees. Maybe add a drop-down list to choose the list the instance should be in so we can easily revoke the guarantee on an instance when it becomes a problem.

**Comment by RikudouSage** [comment]
Regarding the 2nd part, you can remove them at https://gui.fediseer.com/guarantees/my

**Comment by Antik79** [comment]
> Regarding the 2nd part, you can remove them at https://gui.fediseer.com/guarantees/my

I know where to remove them, thanks! :) But if I would "cancel" there might be a reason why.
