### ISSUE TITLE
BUG - "Treat hesitations as censures" doesn't use tag filter

### ISSUE THREAD

**Issue by Antik79** [Fediseer/FediseerGUI#85]
If I tag to only follow for example "csam" and "spam" this will be ignored for hesitations.  Instead the GUI will add all the hesitations.

Example:
- Feddit.uk and Lemmy.one are currently in my censures as "inactive admins".
- For Filter by reasons I fill: "csam"

![image](https://github.com/Fediseer/FediseerGUI/assets/3721299/554d13fa-41af-48ac-925c-a26bde9d7368)

As you see they are both added in the Preview.

**Comment by RikudouSage** [comment]
Your own censures/hesitations are always synchronized in full and ignore the filters. You have to disable treating hesitations as censures. Until Lemmy introduces some more granular options, there's only defederation.
