### ISSUE TITLE
BUG - Blacklist ignore does not work for hesitations

### ISSUE THREAD

**Issue by Antik79** [Fediseer/FediseerGUI#86]
- lemmy.one is currently in my hesitations

![image](https://github.com/Fediseer/FediseerGUI/assets/3721299/4315a5d0-8b97-4ec5-891c-e4fa1e2eba78)

I'm not sure if it's the same for hesitations from other instances as I can not see the difference here.

**Comment by Antik79** [comment]
I'm just testing how those things interact with eachother and how I would expect them to interact :)

**Comment by RikudouSage** [comment]
This works as intended - your own blocklist is synchronized in full, this setting is for imported blocklists. I've added a note that clarifies it in the GUI.

Do you think it would make sense to exclude from your own blocklist as well?
